#! /bin/bash
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
wget -i http://localhost/urls;
