#include "mapreduce.h"

void waitForAll(){
	while(wait(NULL) != -1) {} // Waits for all process to terminate
}

void spawnMapper(int nMappers){
	pid_t pid;
	for(int i = 1; i <= nMappers; i++){ // Iterates through all mappers
		pid = fork();
		// Checks to see if fork worked
		if (pid == -1){
			printf("Could not fork and create mapper.\n");
			exit(1);
		}
		
		if(pid == 0){ 					// Checks to see if current process is the child
			// Creates mapper ID with the current value of 'i' as the ID
			char str[10]; 								// Assumes int wont be greater than 9 digits
			sprintf(str, "%d", i); 						// Converts 'i' to a string for the following exec argument

			execl("./mapper", "mapper", str ,NULL); 						// Spawn mapper process
			printf("Process ID:%d failed to exec mapper.\nExiting.", pid); 	// Prints error message	
			exit(1); 														// Exits if an error occured
		}
	}
}

void spawnReducers(int nReducers){
	pid_t pid;
	for(int i = 1; i <= nReducers; i++){ 		// Iterates through all reducers
		pid = fork();
		// Checks to see if fork worked
		if (pid == -1){
			printf("Could not fork and create reducer.\n");
			exit(1);
		}
		if(pid == 0){ 							// Checks to see if the current process is the child
			// Creates reducer ID with the current value of 'i' as the ID
			char str[10];
			sprintf(str, "%d", i); // Converts 'i' to a string for the following exec argument

			execl("./reducer", "reducer", str, NULL); 							// Spawns reducer process
			printf("Process ID:%d failed to exec reducer.\nExiting.", pid); 	// Prints error message
			exit(1); 															// Exits if error occured
		}
	}
}

int main(int argc, char *argv[]) {
	// Cecks arguments
	if(argc < 4) {
		printf("Less number of arguments.\n");
		printf("./mapreduce #mappers #reducers inputFile\n");
		exit(1);
	}

	// ###### DO NOT REMOVE ######
	int nMappers 	= strtol(argv[1], NULL, 10);
	int nReducers 	= strtol(argv[2], NULL, 10);

	// Checks to see if num reducers is greater than num mappers
	// If so, error out
	if(nMappers < nReducers){
		printf("nMappers < nReducers\n");
		exit(1);
	}
	char *inputFile = argv[3];

	// ###### DO NOT REMOVE ######
	bookeepingCode();

	// ###### DO NOT REMOVE ######
	pid_t pid = fork();
	if(pid == 0){
		//send chunks of data to the mappers in RR fashion
		sendChunkData(inputFile, nMappers);
		exit(0);
	}
	sleep(1);

	// spawn mappers processes and run 'mapper' executable using exec
	spawnMapper(nMappers);

	// wait for all children to complete execution
	waitForAll();

	// ###### DO NOT REMOVE ######
    // shuffle sends the word.txt files generated by mapper
    // to reducer based on a hash function
	pid = fork();
	if(pid == 0){
		shuffle(nMappers, nReducers);
		exit(0);
	}
	sleep(1);


	// spawn reducer processes and run 'reducer' executable using exec
	spawnReducers(nReducers);

	// wait for all children to complete execution
	waitForAll();
	
	return 0;
}
